add_executable(bfs_example bfs_example.cc)
target_link_libraries(bfs_example boost_graph)

add_executable(graph_tutor graph_tutor.cc)
target_link_libraries(graph_tutor boost_graph)

add_executable(astar-cities astar-cities.cc)
target_link_libraries(astar-cities boost_graph)

add_executable(dijkstra_shortest_paths_demo dijkstra_shortest_paths_demo.cc)
target_link_libraries(dijkstra_shortest_paths_demo boost_graph)

add_executable(file_dependencies file_dependencies.cpp)
target_link_libraries(file_dependencies boost_graph)

add_executable(dfs_demo dfs_demo.cpp)
target_link_libraries(dfs_demo boost_graph)

add_executable(efficient_cycle_detector efficient_cycle_detector.cc)
target_link_libraries(efficient_cycle_detector boost_graph glog)

add_executable(six_degree_kevin-bacon six_degree_kevin-bacon.cpp)
target_link_libraries(six_degree_kevin-bacon boost_graph)
