// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alias_level.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_alias_5flevel_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_alias_5flevel_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_alias_5flevel_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_alias_5flevel_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_alias_5flevel_2eproto;
namespace smart_pointer {
class Level1;
class Level1DefaultTypeInternal;
extern Level1DefaultTypeInternal _Level1_default_instance_;
class Level2;
class Level2DefaultTypeInternal;
extern Level2DefaultTypeInternal _Level2_default_instance_;
class Level3;
class Level3DefaultTypeInternal;
extern Level3DefaultTypeInternal _Level3_default_instance_;
}  // namespace smart_pointer
PROTOBUF_NAMESPACE_OPEN
template<> ::smart_pointer::Level1* Arena::CreateMaybeMessage<::smart_pointer::Level1>(Arena*);
template<> ::smart_pointer::Level2* Arena::CreateMaybeMessage<::smart_pointer::Level2>(Arena*);
template<> ::smart_pointer::Level3* Arena::CreateMaybeMessage<::smart_pointer::Level3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace smart_pointer {

// ===================================================================

class Level1 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smart_pointer.Level1) */ {
 public:
  inline Level1() : Level1(nullptr) {}
  virtual ~Level1();

  Level1(const Level1& from);
  Level1(Level1&& from) noexcept
    : Level1() {
    *this = ::std::move(from);
  }

  inline Level1& operator=(const Level1& from) {
    CopyFrom(from);
    return *this;
  }
  inline Level1& operator=(Level1&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Level1& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Level1* internal_default_instance() {
    return reinterpret_cast<const Level1*>(
               &_Level1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Level1& a, Level1& b) {
    a.Swap(&b);
  }
  inline void Swap(Level1* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Level1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Level1* New() const final {
    return CreateMaybeMessage<Level1>(nullptr);
  }

  Level1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Level1>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Level1& from);
  void MergeFrom(const Level1& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Level1* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smart_pointer.Level1";
  }
  protected:
  explicit Level1(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_alias_5flevel_2eproto);
    return ::descriptor_table_alias_5flevel_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOtherFieldNumber = 2,
    kLevel2FieldNumber = 1,
  };
  // optional string other = 2;
  bool has_other() const;
  private:
  bool _internal_has_other() const;
  public:
  void clear_other();
  const std::string& other() const;
  void set_other(const std::string& value);
  void set_other(std::string&& value);
  void set_other(const char* value);
  void set_other(const char* value, size_t size);
  std::string* mutable_other();
  std::string* release_other();
  void set_allocated_other(std::string* other);
  private:
  const std::string& _internal_other() const;
  void _internal_set_other(const std::string& value);
  std::string* _internal_mutable_other();
  public:

  // optional .smart_pointer.Level2 level2 = 1;
  bool has_level2() const;
  private:
  bool _internal_has_level2() const;
  public:
  void clear_level2();
  const ::smart_pointer::Level2& level2() const;
  ::smart_pointer::Level2* release_level2();
  ::smart_pointer::Level2* mutable_level2();
  void set_allocated_level2(::smart_pointer::Level2* level2);
  private:
  const ::smart_pointer::Level2& _internal_level2() const;
  ::smart_pointer::Level2* _internal_mutable_level2();
  public:
  void unsafe_arena_set_allocated_level2(
      ::smart_pointer::Level2* level2);
  ::smart_pointer::Level2* unsafe_arena_release_level2();

  // @@protoc_insertion_point(class_scope:smart_pointer.Level1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr other_;
  ::smart_pointer::Level2* level2_;
  friend struct ::TableStruct_alias_5flevel_2eproto;
};
// -------------------------------------------------------------------

class Level2 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smart_pointer.Level2) */ {
 public:
  inline Level2() : Level2(nullptr) {}
  virtual ~Level2();

  Level2(const Level2& from);
  Level2(Level2&& from) noexcept
    : Level2() {
    *this = ::std::move(from);
  }

  inline Level2& operator=(const Level2& from) {
    CopyFrom(from);
    return *this;
  }
  inline Level2& operator=(Level2&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Level2& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Level2* internal_default_instance() {
    return reinterpret_cast<const Level2*>(
               &_Level2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Level2& a, Level2& b) {
    a.Swap(&b);
  }
  inline void Swap(Level2* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Level2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Level2* New() const final {
    return CreateMaybeMessage<Level2>(nullptr);
  }

  Level2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Level2>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Level2& from);
  void MergeFrom(const Level2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Level2* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smart_pointer.Level2";
  }
  protected:
  explicit Level2(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_alias_5flevel_2eproto);
    return ::descriptor_table_alias_5flevel_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kLevel3FieldNumber = 3,
    kValueFieldNumber = 2,
  };
  // optional string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional .smart_pointer.Level3 level3 = 3;
  bool has_level3() const;
  private:
  bool _internal_has_level3() const;
  public:
  void clear_level3();
  const ::smart_pointer::Level3& level3() const;
  ::smart_pointer::Level3* release_level3();
  ::smart_pointer::Level3* mutable_level3();
  void set_allocated_level3(::smart_pointer::Level3* level3);
  private:
  const ::smart_pointer::Level3& _internal_level3() const;
  ::smart_pointer::Level3* _internal_mutable_level3();
  public:
  void unsafe_arena_set_allocated_level3(
      ::smart_pointer::Level3* level3);
  ::smart_pointer::Level3* unsafe_arena_release_level3();

  // optional int32 value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  ::PROTOBUF_NAMESPACE_ID::int32 value() const;
  void set_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_value() const;
  void _internal_set_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:smart_pointer.Level2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::smart_pointer::Level3* level3_;
  ::PROTOBUF_NAMESPACE_ID::int32 value_;
  friend struct ::TableStruct_alias_5flevel_2eproto;
};
// -------------------------------------------------------------------

class Level3 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smart_pointer.Level3) */ {
 public:
  inline Level3() : Level3(nullptr) {}
  virtual ~Level3();

  Level3(const Level3& from);
  Level3(Level3&& from) noexcept
    : Level3() {
    *this = ::std::move(from);
  }

  inline Level3& operator=(const Level3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Level3& operator=(Level3&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Level3& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Level3* internal_default_instance() {
    return reinterpret_cast<const Level3*>(
               &_Level3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Level3& a, Level3& b) {
    a.Swap(&b);
  }
  inline void Swap(Level3* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Level3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Level3* New() const final {
    return CreateMaybeMessage<Level3>(nullptr);
  }

  Level3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Level3>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Level3& from);
  void MergeFrom(const Level3& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Level3* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smart_pointer.Level3";
  }
  protected:
  explicit Level3(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_alias_5flevel_2eproto);
    return ::descriptor_table_alias_5flevel_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTagFieldNumber = 1,
  };
  // optional string tag = 1;
  bool has_tag() const;
  private:
  bool _internal_has_tag() const;
  public:
  void clear_tag();
  const std::string& tag() const;
  void set_tag(const std::string& value);
  void set_tag(std::string&& value);
  void set_tag(const char* value);
  void set_tag(const char* value, size_t size);
  std::string* mutable_tag();
  std::string* release_tag();
  void set_allocated_tag(std::string* tag);
  private:
  const std::string& _internal_tag() const;
  void _internal_set_tag(const std::string& value);
  std::string* _internal_mutable_tag();
  public:

  // @@protoc_insertion_point(class_scope:smart_pointer.Level3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tag_;
  friend struct ::TableStruct_alias_5flevel_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Level1

// optional .smart_pointer.Level2 level2 = 1;
inline bool Level1::_internal_has_level2() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || level2_ != nullptr);
  return value;
}
inline bool Level1::has_level2() const {
  return _internal_has_level2();
}
inline void Level1::clear_level2() {
  if (level2_ != nullptr) level2_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::smart_pointer::Level2& Level1::_internal_level2() const {
  const ::smart_pointer::Level2* p = level2_;
  return p != nullptr ? *p : *reinterpret_cast<const ::smart_pointer::Level2*>(
      &::smart_pointer::_Level2_default_instance_);
}
inline const ::smart_pointer::Level2& Level1::level2() const {
  // @@protoc_insertion_point(field_get:smart_pointer.Level1.level2)
  return _internal_level2();
}
inline void Level1::unsafe_arena_set_allocated_level2(
    ::smart_pointer::Level2* level2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(level2_);
  }
  level2_ = level2;
  if (level2) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:smart_pointer.Level1.level2)
}
inline ::smart_pointer::Level2* Level1::release_level2() {
  _has_bits_[0] &= ~0x00000002u;
  ::smart_pointer::Level2* temp = level2_;
  level2_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::smart_pointer::Level2* Level1::unsafe_arena_release_level2() {
  // @@protoc_insertion_point(field_release:smart_pointer.Level1.level2)
  _has_bits_[0] &= ~0x00000002u;
  ::smart_pointer::Level2* temp = level2_;
  level2_ = nullptr;
  return temp;
}
inline ::smart_pointer::Level2* Level1::_internal_mutable_level2() {
  _has_bits_[0] |= 0x00000002u;
  if (level2_ == nullptr) {
    auto* p = CreateMaybeMessage<::smart_pointer::Level2>(GetArena());
    level2_ = p;
  }
  return level2_;
}
inline ::smart_pointer::Level2* Level1::mutable_level2() {
  // @@protoc_insertion_point(field_mutable:smart_pointer.Level1.level2)
  return _internal_mutable_level2();
}
inline void Level1::set_allocated_level2(::smart_pointer::Level2* level2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete level2_;
  }
  if (level2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(level2);
    if (message_arena != submessage_arena) {
      level2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, level2, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  level2_ = level2;
  // @@protoc_insertion_point(field_set_allocated:smart_pointer.Level1.level2)
}

// optional string other = 2;
inline bool Level1::_internal_has_other() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Level1::has_other() const {
  return _internal_has_other();
}
inline void Level1::clear_other() {
  other_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Level1::other() const {
  // @@protoc_insertion_point(field_get:smart_pointer.Level1.other)
  return _internal_other();
}
inline void Level1::set_other(const std::string& value) {
  _internal_set_other(value);
  // @@protoc_insertion_point(field_set:smart_pointer.Level1.other)
}
inline std::string* Level1::mutable_other() {
  // @@protoc_insertion_point(field_mutable:smart_pointer.Level1.other)
  return _internal_mutable_other();
}
inline const std::string& Level1::_internal_other() const {
  return other_.Get();
}
inline void Level1::_internal_set_other(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  other_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Level1::set_other(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  other_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:smart_pointer.Level1.other)
}
inline void Level1::set_other(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  other_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:smart_pointer.Level1.other)
}
inline void Level1::set_other(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  other_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:smart_pointer.Level1.other)
}
inline std::string* Level1::_internal_mutable_other() {
  _has_bits_[0] |= 0x00000001u;
  return other_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Level1::release_other() {
  // @@protoc_insertion_point(field_release:smart_pointer.Level1.other)
  if (!_internal_has_other()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return other_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Level1::set_allocated_other(std::string* other) {
  if (other != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  other_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), other,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:smart_pointer.Level1.other)
}

// -------------------------------------------------------------------

// Level2

// optional string name = 1;
inline bool Level2::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Level2::has_name() const {
  return _internal_has_name();
}
inline void Level2::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Level2::name() const {
  // @@protoc_insertion_point(field_get:smart_pointer.Level2.name)
  return _internal_name();
}
inline void Level2::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:smart_pointer.Level2.name)
}
inline std::string* Level2::mutable_name() {
  // @@protoc_insertion_point(field_mutable:smart_pointer.Level2.name)
  return _internal_mutable_name();
}
inline const std::string& Level2::_internal_name() const {
  return name_.Get();
}
inline void Level2::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Level2::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:smart_pointer.Level2.name)
}
inline void Level2::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:smart_pointer.Level2.name)
}
inline void Level2::set_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:smart_pointer.Level2.name)
}
inline std::string* Level2::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Level2::release_name() {
  // @@protoc_insertion_point(field_release:smart_pointer.Level2.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Level2::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:smart_pointer.Level2.name)
}

// optional int32 value = 2;
inline bool Level2::_internal_has_value() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Level2::has_value() const {
  return _internal_has_value();
}
inline void Level2::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Level2::_internal_value() const {
  return value_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Level2::value() const {
  // @@protoc_insertion_point(field_get:smart_pointer.Level2.value)
  return _internal_value();
}
inline void Level2::_internal_set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  value_ = value;
}
inline void Level2::set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:smart_pointer.Level2.value)
}

// optional .smart_pointer.Level3 level3 = 3;
inline bool Level2::_internal_has_level3() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || level3_ != nullptr);
  return value;
}
inline bool Level2::has_level3() const {
  return _internal_has_level3();
}
inline void Level2::clear_level3() {
  if (level3_ != nullptr) level3_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::smart_pointer::Level3& Level2::_internal_level3() const {
  const ::smart_pointer::Level3* p = level3_;
  return p != nullptr ? *p : *reinterpret_cast<const ::smart_pointer::Level3*>(
      &::smart_pointer::_Level3_default_instance_);
}
inline const ::smart_pointer::Level3& Level2::level3() const {
  // @@protoc_insertion_point(field_get:smart_pointer.Level2.level3)
  return _internal_level3();
}
inline void Level2::unsafe_arena_set_allocated_level3(
    ::smart_pointer::Level3* level3) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(level3_);
  }
  level3_ = level3;
  if (level3) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:smart_pointer.Level2.level3)
}
inline ::smart_pointer::Level3* Level2::release_level3() {
  _has_bits_[0] &= ~0x00000002u;
  ::smart_pointer::Level3* temp = level3_;
  level3_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::smart_pointer::Level3* Level2::unsafe_arena_release_level3() {
  // @@protoc_insertion_point(field_release:smart_pointer.Level2.level3)
  _has_bits_[0] &= ~0x00000002u;
  ::smart_pointer::Level3* temp = level3_;
  level3_ = nullptr;
  return temp;
}
inline ::smart_pointer::Level3* Level2::_internal_mutable_level3() {
  _has_bits_[0] |= 0x00000002u;
  if (level3_ == nullptr) {
    auto* p = CreateMaybeMessage<::smart_pointer::Level3>(GetArena());
    level3_ = p;
  }
  return level3_;
}
inline ::smart_pointer::Level3* Level2::mutable_level3() {
  // @@protoc_insertion_point(field_mutable:smart_pointer.Level2.level3)
  return _internal_mutable_level3();
}
inline void Level2::set_allocated_level3(::smart_pointer::Level3* level3) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete level3_;
  }
  if (level3) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(level3);
    if (message_arena != submessage_arena) {
      level3 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, level3, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  level3_ = level3;
  // @@protoc_insertion_point(field_set_allocated:smart_pointer.Level2.level3)
}

// -------------------------------------------------------------------

// Level3

// optional string tag = 1;
inline bool Level3::_internal_has_tag() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Level3::has_tag() const {
  return _internal_has_tag();
}
inline void Level3::clear_tag() {
  tag_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Level3::tag() const {
  // @@protoc_insertion_point(field_get:smart_pointer.Level3.tag)
  return _internal_tag();
}
inline void Level3::set_tag(const std::string& value) {
  _internal_set_tag(value);
  // @@protoc_insertion_point(field_set:smart_pointer.Level3.tag)
}
inline std::string* Level3::mutable_tag() {
  // @@protoc_insertion_point(field_mutable:smart_pointer.Level3.tag)
  return _internal_mutable_tag();
}
inline const std::string& Level3::_internal_tag() const {
  return tag_.Get();
}
inline void Level3::_internal_set_tag(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Level3::set_tag(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  tag_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:smart_pointer.Level3.tag)
}
inline void Level3::set_tag(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:smart_pointer.Level3.tag)
}
inline void Level3::set_tag(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:smart_pointer.Level3.tag)
}
inline std::string* Level3::_internal_mutable_tag() {
  _has_bits_[0] |= 0x00000001u;
  return tag_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Level3::release_tag() {
  // @@protoc_insertion_point(field_release:smart_pointer.Level3.tag)
  if (!_internal_has_tag()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return tag_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Level3::set_allocated_tag(std::string* tag) {
  if (tag != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  tag_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tag,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:smart_pointer.Level3.tag)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace smart_pointer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_alias_5flevel_2eproto
