add_subdirectory(coroutine)
add_subdirectory(beast_network)

add_executable(use_circular_buffer use_circular_buffer.cc)
target_link_libraries(use_circular_buffer boost_system glog)

add_executable(signal2 signal2.cc)
target_link_libraries(signal2 boost_system glog)

add_subdirectory(rtree_demo)
add_subdirectory(bimap)
add_subdirectory(geometry)
add_subdirectory(graph_library)

add_executable(intrusive_list_demo intrusive_list_demo.cc)
target_link_libraries(intrusive_list_demo boost_system glog)

add_executable(icl_party_demo icl_party_demo.cc)
target_link_libraries(icl_party_demo boost_date_time glog)

add_executable(icl_interval_set_demo icl_interval_set_demo.cc)
target_link_libraries(icl_interval_set_demo boost_date_time glog)

add_executable(property_map_demo property_map_demo.cc)
target_link_libraries(property_map_demo boost_system glog)

add_executable(simple_bimap simple_bimap.cc)
target_link_libraries(simple_bimap boost_system glog)

add_executable(stl_concept_check stl_concept_check.cc)
target_link_libraries(stl_concept_check boost_system)

add_executable(check_class_member_method check_class_member_method.cc)
target_link_libraries(check_class_member_method boost_system glog)
